"use client";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { useState } from "react";
import type { IconType } from "react-icons";
import { SiArduino, SiBootstrap, SiC, SiCss, SiDocker, SiFigma, SiFastapi, SiFlask, SiGit, SiGithub, SiHtml5, SiHuggingface, SiIntel, SiJavascript, SiKeras, SiLinux, SiNodedotjs, SiNvidia, SiOpencv, SiOpenjdk, SiPostgresql, SiPostman, SiPytorch, SiPython, SiRaspberrypi, SiReact, SiRos, SiScikitlearn, SiSqlite, SiStreamlit, SiTailwindcss, SiTensorflow, SiUnity, SiWebflow, SiYolo } from "react-icons/si";
import { FaAws } from "react-icons/fa";

const skills = [
  ["Programming Languages", "Python", "Java", "JavaScript", "C", "SQL"], ["Frontend Development", "HTML5", "CSS3", "Tailwind", "Bootstrap", "React"], ["Backend Development", "Flask", "Node.js", "REST APIs", "Streamlit"], ["AI & Machine Learning", "TensorFlow", "PyTorch", "Keras", "Scikit-learn", "Hugging Face"], ["Computer Vision", "OpenCV", "YOLO", "Transformers", "RealSense"], ["Robotics & Embedded", "Arduino", "Raspberry Pi", "ROS", "Pixhawk", "Jetson Nano"], ["Databases", "SQL", "SQLite"], ["Cloud & DevOps", "AWS EC2", "S3", "Lambda", "Docker", "Linux"], ["Design & UI/UX", "Figma", "Adobe XD", "Canva", "Zeplin", "Webflow"], ["Development Tools", "Git", "GitHub", "Postman", "VS Code", "Unity"]
];
const techIcons: Record<string, IconType> = {"Python":SiPython,"Java":SiOpenjdk,"JavaScript":SiJavascript,"C":SiC,"SQL":SiPostgresql,"HTML5":SiHtml5,"CSS3":SiCss,"Tailwind":SiTailwindcss,"Bootstrap":SiBootstrap,"React":SiReact,"Flask":SiFlask,"Node.js":SiNodedotjs,"REST APIs":SiFastapi,"Streamlit":SiStreamlit,"TensorFlow":SiTensorflow,"PyTorch":SiPytorch,"Keras":SiKeras,"Scikit-learn":SiScikitlearn,"Hugging Face":SiHuggingface,"OpenCV":SiOpencv,"YOLO":SiYolo,"Transformers":SiHuggingface,"RealSense":SiIntel,"Arduino":SiArduino,"Raspberry Pi":SiRaspberrypi,"ROS":SiRos,"Jetson Nano":SiNvidia,"SQLite":SiSqlite,"AWS EC2":FaAws,"S3":FaAws,"Lambda":FaAws,"Docker":SiDocker,"Linux":SiLinux,"Figma":SiFigma,"Webflow":SiWebflow,"Git":SiGit,"GitHub":SiGithub,"Postman":SiPostman,"Unity":SiUnity};
const TechLogo = ({ name }: { name: string }) => { const Icon = techIcons[name]; return Icon ? <Icon className="tech-logo" style={{ width: 17, height: 17, color: "currentColor", flex: "0 0 auto" }} aria-label={`${name} logo`} /> : <span className="tech-fallback" style={{ display: "inline-grid", placeItems: "center", width: 17, height: 17, border: "1px solid currentColor", fontSize: 7, fontFamily: "monospace", flex: "0 0 auto" }} aria-label={`${name} logo`}>{name.slice(0,2)}</span>; };
const experience = [
  { period:"MAY 2025 — PRESENT", role:"Software Engineering Intern", company:"ACCEL UAV Private Limited", impact:"Redesigned acceluav.com end-to-end and built RLTM, a real-time 2D telemetry and mission-planning application.", tech:"Figma · HTML/CSS/JS · MAVLink · QGroundControl" },
  { period:"2024 — PRESENT", role:"Freelance UI/UX Designer & Web Developer", company:"Independent", impact:"Partnering with clients from discovery through production builds - portfolios, landing pages, e-commerce UIs and SaaS dashboards.", tech:"Figma · Tailwind · WordPress · Webflow" },
  { period:"2024 — 2025", role:"Team Lead, Autonomous Aerial Robotics", company:"AIREAL / CAS, GITAM", impact:"Led a multidisciplinary team through hardware-software milestones and mentored junior team members.", tech:"ROS · Arduino · Raspberry Pi · Figma" },
  { period:"2022 — 2023", role:"Machine Learning Intern", company:"HMI Technologies", impact:"Developed a fake-review detection system using NLP, sentiment analysis and ML classification, delivered in a Flask app.", tech:"Python · NLP · Flask · Figma" }
];
const projects = [
  {id:"01", name:"Skin Disease Detection", type:"ML PRODUCT", problem:"Make image-based skin classification easier to access.", description:"An end-to-end CNN classifier for melanoma, eczema, psoriasis, ringworm, acne and more, designed as a clear, medical-grade web experience.", tech:"TensorFlow · Keras · Flask · Figma", result:"90%+ validation accuracy", visual:"skin"},
  {id:"02", name:"ACCEL UAV Website", type:"UI/UX + WEB", problem:"Turn a complex defence-UAV offering into a focused, credible digital presence.", description:"Stakeholder research, design system, Figma prototypes and a responsive production build with polished motion and Core Web Vitals in mind.", tech:"Figma · HTML5 · CSS3 · JavaScript", result:"End-to-end redesign", visual:"grid"},
  {id:"03", name:"Precision Landing", type:"COMPUTER VISION", problem:"Help a drone identify and correct its landing position during descent.", description:"OpenCV ArUco detection coupled to a PID visual-servoing loop, simulated in Gazebo before real-world flight testing.", tech:"OpenCV · ArUco · ROS · Gazebo", result:"Sub-10 cm landing accuracy", visual:"target"},
  {id:"04", name:"Crowd Monitoring Drone", type:"EDGE AI", problem:"Surface crowd-density risk zones in real time.", description:"A dual-Raspberry Pi edge-computing build with custom gimbal and AI analysis pipeline. Awarded 3rd place at AI Hackathon 2025.", tech:"YOLO · Raspberry Pi · Pixhawk · Arduino", result:"3rd place / AI Hackathon", visual:"orbit"}
];
const achievements = ["3rd Place — AI Hackathon 2025", "Smart India Hackathon 2024 — Team Lead", "Python Full-Stack Developer", "UI/UX Design Fundamentals", "Intro to Programming", "AIREAL / CAS Leadership"];
const rise = {hidden:{opacity:0,y:24},show:{opacity:1,y:0}};

export default function Home(){
 const [menu,setMenu]=useState(false); const [paperTheme,setPaperTheme]=useState(true); const reduce=useReducedMotion(); const stagger=reduce?{}:{transition:{staggerChildren:.08,delayChildren:.12}};
 return <main className={paperTheme ? "theme-paper" : ""}>
  <style>{`.theme-paper{background:#f7f1e7;color:#17151f}.theme-paper .nav{color:#17151f}.theme-paper .hero{background:radial-gradient(circle at 80% 48%,#ff7a6b80 0,transparent 28%),#f7f1e7;color:#17151f}.theme-paper .hero-orbit{border-color:#5b5be7;box-shadow:inset 0 0 0 45px #5b5be720,0 0 0 70px #ff7a6b20}.theme-paper .hero-meta,.theme-paper .hero-actions{color:#645f6b}.theme-paper .hero h1 em,.theme-paper .hero-copy>p{color:#5b5be7}.theme-paper .button{border-color:#777180}.theme-paper .button.primary{background:#5b5be7;border-color:#5b5be7;color:#f7f1e7}.theme-paper .skills{background:#f7f1e7}.theme-paper .marquee span,.theme-paper .skill-grid p span{color:#17151f}.theme-paper .skill-grid p span{background:#fff}.theme-paper .skill-grid i{background:linear-gradient(90deg,#ff7a6b var(--level),#d9d2c9 var(--level))}.theme-paper .experience{background:#17151f;color:#f7f1e7}.theme-paper .experience .tech-logo,.theme-paper .experience .tech-fallback{color:#f7f1e7}.theme-paper .profile{background:#f7f1e7;color:#17151f}.theme-paper .growth b{color:#17151f}.theme-paper .footer{background:#17151f;color:#aaa4b2}.theme-paper .contact{background:#5b5be7}.theme-paper .mobile-nav{background:#5b5be7;color:#f7f1e7}`}</style>
  <nav className="nav"><a className="brand" href="#home">LKB<span>.</span></a><div className="navlinks">{["Home","Skills","Experience","Projects","Achievements","Profile","Contact"].map(x=><a key={x} href={`#${x.toLowerCase()}`}>{x}</a>)}</div><button className="theme-switch" style={{border:"1px solid currentColor",background:"transparent",color:"inherit",padding:"8px 10px",font:"inherit",fontSize:9,textTransform:"uppercase"}} onClick={()=>setPaperTheme(!paperTheme)} aria-label="Switch website theme">{paperTheme?"Ink mode":"Paper mode"}</button><button className="menu" onClick={()=>setMenu(!menu)} aria-expanded={menu}>Menu {menu?"−":"+"}</button></nav>
  <AnimatePresence>{menu&&<motion.div className="mobile-nav" initial={{opacity:0,y:-15}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-15}}>{["Home","Skills","Experience","Projects","Achievements","Profile","Contact"].map(x=><a key={x} onClick={()=>setMenu(false)} href={`#${x.toLowerCase()}`}>{x}</a>)}</motion.div>}</AnimatePresence>
  <section className="hero" id="home"><div className="hero-orbit"/><motion.div className="hero-meta" initial="hidden" animate="show" variants={stagger}><motion.span variants={rise}>PORTFOLIO / 2026</motion.span><motion.span variants={rise}>VISAKHAPATNAM, INDIA</motion.span></motion.div><motion.div className="hero-copy" initial="hidden" animate="show" variants={stagger}><motion.p variants={rise}>Software Engineer<br/>UI/UX & Web Designer<br/>Freelance Developer</motion.p><motion.h1 variants={rise}>DAMMU LOHITH<br/><em>KRISHNA</em><br/>BHAGAVAN.</motion.h1><motion.div variants={rise} className="hero-intro">I design and build thoughtful digital products - combining software engineering, AI/ML, and a strong eye for interfaces people genuinely enjoy using.</motion.div></motion.div><motion.div className="hero-actions" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.65}}><a className="button primary" href="#projects">View projects <b>↘</b></a><a className="button" href="/Lohith_Krishna_Bhagavan_Resume.pdf" download>Download résumé <b>↓</b></a><a className="button text" href="#contact">Contact me <b>↗</b></a></motion.div></section>
  <section className="skills section" id="skills"><header><span>01</span><p>TECHNOLOGY FIELD NOTES</p><small>10 DISCIPLINES / ALWAYS LEARNING</small></header><div className="marquee" aria-label="Technology carousel"><div>{[...skills.flatMap(x=>x.slice(1)),...skills.flatMap(x=>x.slice(1))].map((skill,i)=><span key={`${skill}-${i}`}><TechLogo name={skill}/>{skill}</span>)}</div></div><div className="skill-grid">{skills.map(([group,...items],i)=><motion.article key={group} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.035}}><div><span>0{i+1}</span><h3>{group}</h3></div><p>{items.map((item,j)=><span className="skill-chip" key={item} style={{"--level":`${88-j*8}%`,display:"inline-flex",alignItems:"center",gap:6,minHeight:36,padding:"7px 9px"} as React.CSSProperties}><TechLogo name={item}/><b style={{fontWeight:500}}>{item}</b><i/></span>)}</p></motion.article>)}</div></section>
  <section className="experience section" id="experience"><header><span>02</span><p>EXPERIENCE / IN PRACTICE</p><small>2022 — NOW</small></header><div className="timeline">{experience.map((item,i)=><motion.article key={item.role} initial={{opacity:0,x:-22}} whileInView={{opacity:1,x:0}} viewport={{once:true}}><div className="timeline-mark">{String(i+1).padStart(2,"0")}</div><div className="timeline-period">{item.period}</div><div className="timeline-main"><p>{item.company}</p><h2>{item.role}</h2><p className="impact">{item.impact}</p><small>{item.tech}</small></div></motion.article>)}</div></section>
  <section className="projects section" id="projects"><header><span>03</span><p>SELECTED CASE STUDIES</p><small>IDEA → BUILT</small></header><div className="project-grid">{projects.map((project,i)=><motion.article className="case" key={project.id} initial={{opacity:0,y:28}} whileInView={{opacity:1,y:0}} viewport={{once:true}} whileHover={reduce?undefined:{y:-7}}><div className={`case-visual ${project.visual}`}><span>{project.id}</span><div className="mockup"><i/><i/><i/></div></div><div className="case-type">{project.type}<b>↗</b></div><h2>{project.name}</h2><p><strong>Problem</strong>{project.problem}</p><p>{project.description}</p><footer><span>{project.tech}</span><b>{project.result}</b></footer></motion.article>)}</div></section>
  <section className="achievements section" id="achievements"><header><span>04</span><p>RECOGNITION & MILESTONES</p><small>BUILDING MOMENTUM</small></header><div className="achieve-grid">{achievements.map((item,i)=><motion.article key={item} initial={{rotate:-4,opacity:0}} whileInView={{rotate:i%2?2:-2,opacity:1}} whileHover={{rotate:0,y:-7}} viewport={{once:true}}><span>0{i+1}</span><h2>{item}</h2><p>{i===0?"Awarded for an AI-powered crowd monitoring system.":i===1?"Inclusive video-call intercom concept for the Deaf community.":"A marker of continuous hands-on learning and contribution."}</p></motion.article>)}</div></section>
  <section className="profile" id="profile"><div className="profile-stamp">LKB<br/><span>2026</span></div><div><p className="eyebrow">05 / PROFILE</p><h2>A career built by <em>making</em>, testing, and asking better questions.</h2><p className="profile-copy">I began with a curiosity for how software can solve practical problems. That led me through design systems, full-stack builds, computer vision experiments, and collaborative robotics work. I’m motivated by the gap between a complex idea and an experience that feels natural.</p><div className="growth"><span>2020<br/><b>Computer engineering</b></span><span>2022<br/><b>ML foundations</b></span><span>2024<br/><b>Design & client work</b></span><span>2025+<br/><b>Software engineering</b></span></div></div></section>
  <section className="contact" id="contact"><div><p className="eyebrow">06 / OPEN CHANNEL</p><h2>Let’s make something<br/><em>useful.</em></h2><p>Have a project, product, or idea that deserves care? I’d like to hear about it.</p><div className="contact-links"><a href="mailto:lohithkrishnabhagavan95@gmail.com">Email ↗</a><a href="tel:+917997143693">+91 7997143693</a><a href="https://www.linkedin.com/in/lohtith" target="_blank">LinkedIn ↗</a><a href="/Lohith_Krishna_Bhagavan_Resume.pdf" download>Download résumé ↓</a></div></div><form action="mailto:lohithkrishnabhagavan95@gmail.com" method="post" encType="text/plain"><label>Name<input name="name" required placeholder="Your name"/></label><label>Email<input name="email" type="email" required placeholder="you@company.com"/></label><label>Message<textarea name="message" required placeholder="Tell me a little about the project."/></label><button className="button primary" type="submit">Send message ↗</button></form></section>
  <footer className="footer"><span>© 2026 DAMMU LOHITH KRISHNA BHAGAVAN</span><div><a href="#home">Home</a><a href="#projects">Projects</a><a href="#contact">Contact</a></div></footer>
 </main>
}
